### PR TITLE
Hydra skip

### PR DESCRIPTION
**Pull request by brettviren**
This is to try to solve #148 by finally finishing support for the "hydra" flow graph node category.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
Thanks @brettviren, this would be very useful once available.

As we chatted, I want to make a note here for your debugging.
jsonnet: https://www.phy.bnl.gov/~yuhw/dunefd/hydra-skip/wct-sim-fans-hydra.jsonnet
vis: https://www.phy.bnl.gov/~yuhw/dunefd/hydra-skip/wct-sim-fans-hydra.pdf
error with tbb: https://www.phy.bnl.gov/~yuhw/dunefd/hydra-skip/hydra-tbb.log

**Comment by brettviren** [comment]
@HaiwangYu I added `test_hydra_input.cxx` to try to exercise the hydra front end in a stand alone way.  So far it only seems to run the last out of two sources.  Maybe the test is wrong or maybe hydra is.

**Comment by HaiwangYu** [comment]
Hi @brettviren, if you are OK, I want to resolve the conflict and merged this PR.

**Comment by brettviren** [comment]
@HaiwangYu that would be very welcome, thank you.

**Pull request merged**
