### PR TITLE
Fix issue #211

### PR DESCRIPTION
**Pull request by brettviren**
This needs to be applied on top of PR #199 (aka, it includes all those commits).

See last commit for details of the fix.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
@brettviren, I got some error trying to run the uboone-img test:
Screenshot 2023-04-18 at 2 58 27 PM

Which is related to no trace summary. Maybe you forgot to update the frame input [here](https://www.phy.bnl.gov/~bviren/tmp/wcttest/data_repo/)?

Screenshot 2023-04-18 at 2 58 56 PM

**Comment by HaiwangYu** [comment]
The sim/sigproc tests seem OK. Just the sigproc results fluctuate again.

image

More notes: [pr214.pdf](https://github.com/WireCell/wire-cell-toolkit/files/11268220/pr214.pdf)

The Charge Solving results have much better consistency with WCP for multi-blob solving now:
Screenshot 2023-04-18 at 11 30 55 PM

**Comment by brettviren** [comment]
Hi @HaiwangYu

>  Maybe you forgot to update the frame input

I think you are right.  At least, the `img/test/test-wct-uboone-img.bats` test passes with my local "test data repo".  

I've just refreshed the `input` and `history` tar files at  https://www.phy.bnl.gov/~bviren/tmp/wcttest/data_repo/

Hopefully your running of the test will work now.  To assure fresh download, you may need to:

```
rm -r build/tests/input*
```

Aside comment:

This out-of-sync problem would have been avoided if I remembered to do a `distclean` before a final test of the PR.  But, fundamentally, the current form of the "test data repo" has no mechanism to tie its content to a particular git commit.  For example, the new tar files I just uploaded likely break older versions of WCT tests in the git history.  To provide a stronger connection between code and data versions I think the test data repo needs to move to something based on either `git-annex` or `git-lfs`.  For the near ter, I think we continue to use tar files in a HTTP directory.  Hopefully I can put something better before the next release, or perhaps the next-next one.  I just made #215 to capture this.

**Comment by HaiwangYu** [comment]
@brettviren, I still get an error which seems to be related to the numpy json diff test. But I think we could merge this PR first?
Screenshot 2023-04-19 at 4 16 29 PM

**Comment by brettviren** [comment]
Yes, I think it is okay to merge.  I'll just go ahead and do that.  I'll look at checking the json vs numpy format test more.

**Pull request merged**
