### PR TITLE
Prepare for hybrid full chain with wc/ls stage separate from follow-on pure-WCT stage

### PR DESCRIPTION
**Pull request by brettviren**
This starts by adding depo tar streams to gain better compression than what cnpy provides (none).

It also includes one small tweak to `DepoBagger` which will bag all depos regardless of their time if the time "gate" is [0,0].  For existing configs, this will not change behavior.

Draft for now as I work out any more issues along the way to a full hybrid job.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
Hi @brettviren, sorry for the delay.

One thing I noticed first is that the gpvm UPS version of libtorch doesn't have cuda support. So maybe we need to add `#ifdef HAVE_CUDA_INC` around [here](https://github.com/WireCell/wire-cell-toolkit/blob/ad74e1436f695e14e1aeae2abc23db2f9d6f231e/pytorch/src/TorchService.cxx#L99) and [here](https://github.com/WireCell/wire-cell-toolkit/blob/ad74e1436f695e14e1aeae2abc23db2f9d6f231e/pytorch/src/TorchService.cxx#L127)?

Otherwise, the compiling would fail with the gpvm libtorch
```
In file included from /cvmfs/larsoft.opensciencegrid.org/products/libtorch/v1_6_0b/Linux64bit+3.10-2.17-e20/include/c10/cuda/CUDACachingAllocator.h:4,
                 from ../pytorch/src/TorchService.cxx:99:
/cvmfs/larsoft.opensciencegrid.org/products/libtorch/v1_6_0b/Linux64bit+3.10-2.17-e20/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
    6 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```
I am still working on other testings and evaluations of this PR.

**Comment by brettviren** [comment]
Oh, good catch.  Actually, based on our discussion, I meant to remove that cache purge which will also remove this explicit dependency.  Since I've been developing on top of this branch for the upcoming `IDFT` component and we won't make a release immediately, I'll commit a fix there.  Unless not having it here is a blocker.

**Comment by HaiwangYu** [comment]
> Since I've been developing on top of this branch for the upcoming IDFT component and we won't make a release immediately, I'll commit a fix there.

For sure, that works too.

**Review by HaiwangYu — COMMENTED** [review]
Hi @brettviren, I marked several small things. Most are just for myself.
I think we can merge it and fix them later.

Did some tests here:
https://www.phy.bnl.gov/~yuhw/wct-analysis/ml-sp/hybrid-wcls-test

**Pull request merged**
