### PR TITLE
Add support for new ways to configure `Xregion` bounds for #329

### PR DESCRIPTION
**Pull request by brettviren**
- [x] new `CoordRegion` and `CoordBounds` in util
- [x] doctest for that new code
- [x] integration into `Drifter`
- [x] doctest for `Drifter` changes

### CODE REVIEW

**Comment by brettviren** [comment]
Hi @wenqiang-gu 

I feel this is ready now.  Please take a look and see if it satisfies you for #329.

**Comment by wenqiang-gu** [comment]
@brettviren I really like the new `Xregion`. I’ll need to test it for backward compatibility within the jsonnet configuration.

By the way, you’ve provided great examples for implementing CoordBounds. If the SBN folks have a different partitioning scheme, such as rectangular partitioning, would it make sense to declare a new class, like `class CoordBoundRectPart: public CoordBounds`?

**Comment by wenqiang-gu** [comment]
I conducted a quick test using pdsp/wct-sim-check.jsonnet using the following setting:
```jsonnet
charge: -500, 
ray: params.det.bounds, 
step=0.1*wc.mm,
sn_pipes = sim.signal_pipelines, // signal only
```

Here is a comparison of the simulated waveforms:
image
Left: Waveform with the old Xregion
Right: Waveform difference between the old Xregion and the new Xregion

The difference is minimal, at most +/- 1 ADC, indicating consistent results.

**Comment by wenqiang-gu** [comment]
@brettviren I am fine with this PR, please feel free to merge.

**Pull request merged**
