### PR TITLE
Issue #54

### PR DESCRIPTION
**Pull request by brettviren**
This holds the work toward issue #54.  It's still a work in progress.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
I noticed `ZioTorchScript` was removed. I think you planed some different ways to do this. Maybe we could discuss tomorrow?

**Comment by brettviren** [comment]
I have `ITensor -> flow -> hdf` and back working.  On the ZIO side I still need to figure out a more graceful shutdown procedure for the broker but that doesn't have direct impact on the WCT side.  

Assuming no cosmetic conflicts, I think this is ready to look over and then merge.

**Comment by brettviren** [comment]
@HaiwangYu not much changed since your last review so maybe the one I just requested is pro-forma.  If all is okay let's merge!

**Comment by HaiwangYu** [comment]
Thanks @brettviren , let's merge it and I will start to work on #56 based on it.

**Comment by brettviren** [comment]
Thanks!  Note, for #54 we still need to make a job config that runs some simple sim into HDF.  This PR just takes care of the "guts" for that job.

**Pull request merged**
