### PR TITLE
`ITensor` and nanoflann friendly point cloud

### PR DESCRIPTION
**Pull request by brettviren**
This provides a "point cloud" data structure which allows easy and efficient connection to `ITensor` representation but also allows use with `nanoflann` for which it already provides a "dataset adaptor" and includes copy of `nanoflann.hpp`.

Some things still to do before ready for merge:

- [x] add docs
- [x] add to/from `ITensor` in `aux`.
- [x] add `nanoflann` interface  including a connection between a dataset `append()` and notifying the k-d tree ("dynamic adaptor" pattern).
- [x] add more tests for basic PC and the two above.
- ~if inspiration strikes, add connection to graph representation with edges between PC points.~ (will put this off)

### CODE REVIEW

**Comment by brettviren** [comment]
@HaiwangYu this is ready for consideration.  It's late in the day on Friday so don't rush to do it today.

I wrote a note documenting what is in here.  The PDF is committed 

https://github.com/WireCell/wire-cell-toolkit/blob/90b8df6cf71b2022e9292aea14c98715f9db331d/util/docs/point-cloud.pdf

**Comment by brettviren** [comment]
It seems to becoming a bad habit of mine, but I want to do more on this PR.  

In particular, as I think about how the heuristic pipelines will work, I want to add something to better manage the case when they want to add new data arrays or new points.  

Both need some kind of "back filling" mechanism.  Ie, old points need values of a new data type and old data arrays need to be extended for new points.  This back filling is something to live outside the `Dataset` but may require changes in `Dataset` so best I not encourage its use quite yet.

In principle, it could be the job of the heuristic functions to always do the right thing.  However, this would break encapsulation strategy.  Eg, a heuristic H2 adding points would have to know how to back fill data types added by an earlier H1.  H1's data types may be unrelated to H2's operation.

**Comment by brettviren** [comment]
Hi @HaiwangYu 

I think we can consider this for a merge now.  As we discussed in our meeting, it still lacks one example heuristic function `PointGraphVisitor`  but we will put that on hold.

**Comment by brettviren** [comment]
@HaiwangYu I'd like to merge this asap.  I'm starting to need bits here for #195.  I know it's kind of the middle of things but do you have objections?

**Comment by HaiwangYu** [comment]
Hi @brettviren, sure, I will check and merge it later today.

**Comment by HaiwangYu** [comment]
@brettviren, I tried to compile this branch with the container + cvmfs, it complained about missing `<backtrace.h>`, any suggestions?
Screen Shot 2023-01-13 at 9 44 04 AM

**Comment by brettviren** [comment]
@HaiwangYu ah, right.  That originates here:

https://github.com/WireCell/wire-cell-toolkit/blob/point-cloud/util/inc/WireCellUtil/Exceptions.h#L22

The direct fix would be to install `libbacktrace` which I thought was pretty generically available.

But, since you don't have it, perhaps that indicates it is less common than I thought and I should make it an optional build-time option?

**Comment by HaiwangYu** [comment]
I think an option would be very helpful, at least for now, since this package is not available on gpvms too.

**Comment by brettviren** [comment]
Just to be quick, I turn off this feature for now.  I can make it optional later.

**Comment by HaiwangYu** [comment]
Thanks! It complaints about something else now:
Screen Shot 2023-01-13 at 3 45 13 PM

**Comment by brettviren** [comment]
`boost::span` came in Boost 1.78.  Okay, I guess I need to come up with some work-around.

**Comment by HaiwangYu** [comment]
gen and sigproc tested, compared to current `master` (`pr186`)
results looks OK.
https://www.phy.bnl.gov/~yuhw/wct-ci/gen/pr187/
https://www.phy.bnl.gov/~yuhw/wct-ci/sigproc/pr187/

**Pull request merged**
