### PR TITLE
init ZioTorchScript

### PR DESCRIPTION
**Pull request by HaiwangYu**
This PR adds a zio domo client based `ITorchScript` service: `ZioTorchScript`.
More refer to [this talk](https://indico.bnl.gov/event/8124/contributions/36035/)

Things changed after this talk:
- `ITorchScript::forward` is now using `WireCell::ITensorSet` interface
- `WireCell::ITensorSet` is now corresponding to `std::vector<torch::IValue>` both ways
- utility functions are now in pytorch/Util

We now make the zio depends on pytorch, this could be changed later.

Corresponding domo workers and test utilities:
- https://github.com/HaiwangYu/wct-analysis/tree/master/zio
- https://github.com/HaiwangYu/wct-analysis/tree/master/ml-sp

### CODE REVIEW

**Comment by HaiwangYu** [comment]
I feel it is probably better have new packages depends on both, e.g. zio/pytorch or zio/hio.
This way the dependency tree has more granularity and could be configured more easily for different environment. I am not sure if there is a clear downside for this arrangement.

**Comment by brettviren** [comment]
I agree.  The only potential downside is if we imagine scaling this strategy to cases with more than 2 dependencies as it is combinatoric.

Of course, if we start thinking of N>2 big dependencies we might realize we aren't keeping things decoupled as well as we could!

But, really, the pytorch and hdf side of things should be depending only on ZIO (and pytorch/hdf itself) and not WCT at all.  We might consider splitting off these "backends" into new stand-alone packages like "zio-hdf5" or "zio-torch", etc.  We'd then have `wct/zio/` holding any WCT "frontend" components.

**Comment by HaiwangYu** [comment]
Aha, I see. I noticed with the `ITorchScript::forward` using `ITensorSet`, we could move `ITorchScript` to `iface` (no need to depend on pytorch). Then the zio doesn't need to depend on `pytorch` any more, making it a pure WireCell zio front end.

**Comment by brettviren** [comment]
Hmm, actually, do you need a very special interface?  How about making a new `ITensorSetFilter` which would look like an `IFrameFilter` but pass `ITensorSet` instead of `IFrame`?  

Although this interface would be an `INode`, I think that should not stop `DNNROIFinding` from asking the factory for it and using it like a "service".

I guess one question is if the `gpu()` and `ident()` methods are really needed?  If not, then I think using a more generic `ITensorSetFilter` would be good.

**Comment by HaiwangYu** [comment]
Good point. Right now, the ident() and gpu() are not used. I can work on transform that `ITorchScript` to  `ITensorSetFilter`.

**Pull request merged**
