### PR TITLE
Compiler error and some DNNROI related updates

### PR DESCRIPTION
**Pull request by HaiwangYu**

### CODE REVIEW

**Comment by HaiwangYu** [comment]
tested OK:
https://indico.bnl.gov/event/25041/

**Comment by brettviren** [comment]
Hi @HaiwangYu 

I think this PR is okay but the lack of `torch::Tensor::index()` in v1.6 surprises me.  Is there really no way to index tensors in torch 1.6?  I know one can construct a strongly typed and dimensioned "accessor", at least in LibTorch 2.x, but this lacks the "pythonic" indexing syntax.

https://pytorch.org/cppdocs/notes/tensor_basics.html#efficient-access-to-tensor-elements

**Comment by HaiwangYu** [comment]
There could be alternatives like `index_select`? Haven't tried that yet.

**Review by wenqiang-gu — APPROVED** [review]
I reviewed the code in OmnibusSigProc, and everything looks good to me.

**Pull request merged**
