### PR TITLE
Fix spdlog fmtlib

### PR DESCRIPTION
**Pull request by brettviren**
This fixes https://github.com/WireCell/wire-cell-spack/issues/12

### CODE REVIEW

**Comment by brettviren** [comment]
@HaiwangYu it's hard for me to test on old spdlog with built-in fmtlib but hopefully it now compiles for you.

**Comment by HaiwangYu** [comment]
Now the errors changed for me (spdlog 1.8.2):
https://www.phy.bnl.gov/~yuhw/larsoft925/src/wct-latest/log

**Comment by brettviren** [comment]
@HaiwangYu sorry for the iteration on this.  I have a new try which should work.  Tested on various versions of spdlog/fmtlib as described in the wire-cell-spack Issue.  Though, those tests were done outside of WCT so there is still room for something to go wrong.

**Comment by HaiwangYu** [comment]
Hi @brettviren, it almost worked for me with only this:
```bash
../util/test/test_rayclustering.cxx:3:10: fatal error: fmt/core.h: No such file or directory
    3 | #include <fmt/core.h>
      |          ^~~~~~~~~~~~
compilation terminated.

[757/757][100%][/][==================================================================================>][4.794s]
Waf: Leaving directory `/home/yuhw/wc/larsoft925/src/wct-latest/build'
Build failed
 -> task in 'test_rayclustering' failed with exit status 1 (run with -v to display more information)
```

**Comment by brettviren** [comment]
@HaiwangYu this was a stray direct include that is apparently not even needed.  I just pushed a commit to remove it.  Please try one more time.

**Comment by HaiwangYu** [comment]
Thanks! It now compiles and Sim/SigProc seems to be correct.
[wirecell pr296.pdf](https://github.com/WireCell/wire-cell-toolkit/files/15493834/wirecell.pr296.pdf)

**Pull request merged**
