### PR TITLE
Collect work towards imaging and prep for gnn

### PR DESCRIPTION
**Pull request by brettviren**
Some things this PR may provide

- [x] Validated `ICluster` writing to support reading into PyTorch-Geometric data
- [x] Configuration to support depos-sim-sigproc-img jobs using new "layers" config
- [x] Support for porting of WCP deghosting

### CODE REVIEW

**Comment by brettviren** [comment]
Here is an example usage of the new WCT Cluster Array File in Python

``` python

from wirecell.img import tap
gen = tap.load("/home/bv/wrk/wct/imaging/toolkit/clusters-img-3.npz")
for one in gen:
    print(f'one ICluster: {one.keys()}')

#--> one ICluster: dict_keys(['channel', 'wire', 'slice', 'blob', 'measure', ('channel', 'cw', 'wire'), ('blob', 'bs', 'slice'), ('blob', 'bw', 'wire'), ('blob', 'bb', 'blob'), ('channel', 'cm', 'measure'), ('blob', 'bm', 'measure')])

one['blob'].x.shape
#--> (531, 9)

one['blob','bb','blob'].edge_index.shape
#--> (518, 2)
```

**Comment by brettviren** [comment]
@HaiwangYu This is at a good state to merge now.  I've got some slides to describe the new `BlobDepoFill` it provides which I could give a the next WC meeting (or next-next if we skip for the uboone collab meeting).

**Comment by HaiwangYu** [comment]
@brettviren, thanks a lot! I will work on testing this PR.

**Comment by brettviren** [comment]
@HaiwangYu with that last push, the new `BlobShadow` is in with some testing and docs.  I could present it next week or whenever. 

I'll probably cool off on this thread of development for a while so unlikely to want to push any more to this PR anytime soon.  I'll start whatever is the next thing on a new PR.  

So, please take a look when you next have some time. Thanks!

**Comment by HaiwangYu** [comment]
@brettviren, I checked this PR is not breaking anything. Will follow up on the new functionalities.

Img: https://www.phy.bnl.gov/twister/bee/set/722b7dc3-c5b2-498e-8645-ebc8d4a5a2cf/event/list/

[sim-sigproc.pdf](https://github.com/WireCell/wire-cell-toolkit/files/9479185/pr-175.pdf)

**Pull request merged**
