### PR TITLE
Apply pointcloud

### PR DESCRIPTION
**Pull request by brettviren**
@HaiwangYu 

I think we should merge `apply-pointcloud` in to `master`.  The two branches are starting to diverge.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
OK, I will do some tests and merge it.

**Comment by brettviren** [comment]
Here's a bee showing the latest results:

clusters

**Comment by brettviren** [comment]
https://www.phy.bnl.gov/twister/bee/set/b81aa174-d631-42c9-9a24-01fda718aaa0/event/6501/

**Comment by HaiwangYu** [comment]
Test results before merging:
```bash
$SPDLOG_LEVEL=debug ./build/img/wcdoctest-img -tc="clustering facade"
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
[2024-05-17 16:06:16.326] [wct] [debug] pc1: 10
[2024-05-17 16:06:16.327] [wct] [debug] pc2: 10
[2024-05-17 16:06:16.327] [wct] [debug] blob 0: q=1, r=0.5
[2024-05-17 16:06:16.327] [wct] [debug] blob 1: q=2, r=1.5
[2024-05-17 16:06:16.327] [wct] [debug] expect average pos 1.1666666666666667
[2024-05-17 16:06:16.327] [wct] [debug] ave_pos: (1.16667 0 0) | expecting (1.1666666666666665 0 0)
[2024-05-17 16:06:16.327] [wct] [debug] vdir_alg0: (0.999946 0.0087264 0.00555556) | expecting around {1, 0, 0}
[2024-05-17 16:06:16.328] [wct] [debug] vdir_alg1: (0.999924 0.0087262 -0.00872654) | expecting around {1, 0, 0}
[2024-05-17 16:06:16.328] [wct] [debug] length: 8.503120030318284 | expecting 8.50312003032
[2024-05-17 16:06:16.328] [wct] [debug] earliest_latest_points: (0 0 0) (1.9 0 0) | expecting (0 0 0) (1.9 0 0)
[2024-05-17 16:06:16.328] [wct] [debug] num_points: 15 5 | expecting 15, 5
===============================================================================
[doctest] test cases:  1 |  1 passed | 0 failed | 2 skipped
[doctest] assertions: 14 | 14 passed | 0 failed |
[doctest] Status: SUCCESS!
```

uboone test:
log: 
[may-17.log](https://github.com/WireCell/wire-cell-toolkit/files/15357842/may-17.log)
BEE
https://www.phy.bnl.gov/twister/bee/set/b2ebf761-7724-4b7a-928a-26532c5cc6fc/event/6501/

**Pull request merged**
