### PR TITLE
Add 2D interval map

### PR DESCRIPTION
**Pull request by brettviren**
This adds a `Rectangles` class.  See `util/docs/rectangles.org` for information.

It is general purpose but intended to be helpful in optimizing pair-wise comparisons of many projections of 3D blob clusters onto a view.

### CODE REVIEW

**Comment by brettviren** [comment]
Let me add to this some support, docs and tests for a 2D `find()` method similar to the 1D version that Boost provides.

**Comment by brettviren** [comment]
Okay, @HaiwangYu I think I'll stop here.  Please take a look to see if it makes sense to use.  Here's a quick link to the docs:

https://github.com/WireCell/wire-cell-toolkit/blob/interval-tree/util/docs/rectangles.org

**Comment by brettviren** [comment]
Sorry, I go back to draft.  

I want to make `Rectangles` support different data types for its "x" and "y" key types (eg, slice time and wire/channel index).

Easy enough but I also have an idea how to extend "blob shadows" to "cluster shadows" which I just realized could use `Rectangles` as a way to collect the results.  In developing that I may find other improvements to `Rectangles`.

But @HaiwangYu please let me know if delays in this PR become a bottleneck for your projection-based shadowing work and I can expedite the `Rectangles` part.

**Comment by brettviren** [comment]
@HaiwangYu feel free to merge if/when happy.  

I still want to add something new which ties the 2D interval map `Rectangles` to the signal they cover as we discussed.  Depending our your and my timing either I'll sneak that in here or start a new PR.

**Comment by HaiwangYu** [comment]
Thanks @brettviren, compiled for me and seems there are only added stuff. Let's merge it.

**Pull request merged**
