### PR TITLE
New aux package with initial support for ITensor/IFrame conversion.

### PR DESCRIPTION
**Pull request by brettviren**
The idea for this new package is to also cover issue #42.

### CODE REVIEW

**Comment by HaiwangYu** [comment]
I tested this PR with a TBB multithreading job. The job crashed with some `fftw` related stuff. Single-threaded job seems OK.
image

Also, I tested current master, #40 .  It also crashes multithreading jobs at a later stage with `hdf5` related stuff:
image

**Comment by HaiwangYu** [comment]
Let's merge it first and evolve form there.

**Comment by brettviren** [comment]
Thanks. I guess it must be related to changes I made to waf-tools along the way.  Maybe FFTWTHREADS package is getting missed.  I'll look into it.

**Comment by brettviren** [comment]
This was indeed a regression I made that lost `HAVE_FFTWTHREADS_LIB` define.  It's fixed in waf-tools and a new `wcb` is pushed to wire-cell-toolkit.

**Comment by HaiwangYu** [comment]
Thanks for the update. After some testing, the fftw related multi-threading issue was solved after this fix. However, the h5cpp MT related issue still exists. But this is more likely rooted from the h5cpp threading behavior - before #40 , the tests I am using just accidentally doesn't crash MT. I will work on the hio package to make sure h5cpp calls work in MT.

**Pull request merged**
