### PR TITLE
Apply pointcloud

### PR DESCRIPTION
**Pull request by brettviren**
This PR provides the support for the porting of WCP point cloud to WCT and at least initial implementation of some of the algorithms.  It is expected to include at least the basic supporting elements:

- [ ] filling a PC from blobs that is equivalent to WCP's `WCPointCloud`, `WC2DPointCloud` and `CTPointCloud`.
- [ ] a way to "store" object pointers in a WCT PC through associative indices into a collection of objects.
- [ ] implementation of Hough transform for nearby directional estimation.
- [X] PCA

### CODE REVIEW

**Comment by brettviren** [comment]
Hi @HaiwangYu 

I think we should merge this now despite it mostly being about cluster I/O.  This will allow `master` to be in sync with the changes I pushed to `wire-cell-python` a few days ago.  Please let me know if you see any show-stoppers.

Once merged, I can re-open the PR and continue to provide the work actually intended for this PR before the cluster I/O "sidetrack".

This PR also needs #220 resolved.  I can take this on if you have not yet started on it.

**Comment by brettviren** [comment]
Related #150

**Comment by HaiwangYu** [comment]
Hi @brettviren, I got some error when compiling. 
[log.txt](https://github.com/WireCell/wire-cell-toolkit/files/11466735/log.txt)

**Comment by HaiwangYu** [comment]
> This PR also needs https://github.com/WireCell/wire-cell-toolkit/issues/220 resolved. I can take this on if you have not yet started on it.

Sure, it will be great if you can work on it. I think our current choice is to remove the `threshold` tag and move the RMS summary to `wiener`, right?

**Comment by brettviren** [comment]
Thanks, @HaiwangYu 

>  got some error when compiling.

This seems to be some problem with Eigen.  What version is being used in your build?  I am using 3.4.0.

**Comment by HaiwangYu** [comment]
Thanks @brettviren, I confirm I can compile and run a imaging job with `boost v1_75_0` and `eigen v3_4_0` (`boost v1_73_0` or `eigen v3_3_9` fails). I will merge it and do more thorough tests later.

**Pull request merged**
